apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: gatewaypos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # Opciones: NodePort, LoadBalancer, ClusterIP (según tus necesidades)
